dist: trusty
sudo: required

language: c

os: linux

compiler: 
    - gcc

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
    - CODECOV_TOKEN="9d2553ea-9526-4476-b63e-2dc56fdf3f9c"

install:
    - sudo apt-get install -y libgtest-dev valgrind cmake
    - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - tar xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - cmake -DBUILD_SHARED_LIBS=ON .
    - make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - which valgrind
    - cd "${TRAVIS_BUILD_DIR}"
    - sudo apt-get install cppcheck

script:
    - cmake CMakeLists.txt
    - make
    - ./run_tests_sequential
    - ./run_tests_parallel
    - ./iz2_s -s
    - ./iz2_p -p
    - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./iz2_s -s
    - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./iz2_p -p
    - gcov parallel.c sequential.c

after_success:
    - bash <(curl -s https://codecov.io/bash)
